//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M2E.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreateTemplateFacebookLike
    {
        public int Id { get; set; }
        public string username { get; set; }
        public string type { get; set; }
        public string description { get; set; }
        public string referenceId { get; set; }
        public string totalThreads { get; set; }
        public string completed { get; set; }
        public string verified { get; set; }
        public string creationTime { get; set; }
        public string title { get; set; }
        public string subType { get; set; }
        public string payPerUser { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string pageId { get; set; }
        public string pageUrl { get; set; }
    }
}
