//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M2E.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreateTemplateQuestionInfo
    {
        public CreateTemplateQuestionInfo()
        {
            this.CreateTemplateSingleQuestionsLists = new HashSet<CreateTemplateSingleQuestionsList>();
            this.CreateTemplateeditableInstructionsLists = new HashSet<CreateTemplateeditableInstructionsList>();
            this.CreateTemplateImgurImagesLists = new HashSet<CreateTemplateImgurImagesList>();
            this.CreateTemplateListBoxQuestionsLists = new HashSet<CreateTemplateListBoxQuestionsList>();
            this.CreateTemplateModeratingImagesLists = new HashSet<CreateTemplateModeratingImagesList>();
            this.CreateTemplateMultipleQuestionsLists = new HashSet<CreateTemplateMultipleQuestionsList>();
            this.CreateTemplateTextBoxQuestionsLists = new HashSet<CreateTemplateTextBoxQuestionsList>();
        }
    
        public int Id { get; set; }
        public string username { get; set; }
        public string type { get; set; }
        public string visible { get; set; }
        public string description { get; set; }
        public string referenceId { get; set; }
        public string totalThreads { get; set; }
        public string completed { get; set; }
        public string verified { get; set; }
        public string creationTime { get; set; }
        public string title { get; set; }
        public string subType { get; set; }
        public string payPerUser { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public int UserId { get; set; }
    
        public virtual ICollection<CreateTemplateSingleQuestionsList> CreateTemplateSingleQuestionsLists { get; set; }
        public virtual ICollection<CreateTemplateeditableInstructionsList> CreateTemplateeditableInstructionsLists { get; set; }
        public virtual ICollection<CreateTemplateImgurImagesList> CreateTemplateImgurImagesLists { get; set; }
        public virtual ICollection<CreateTemplateListBoxQuestionsList> CreateTemplateListBoxQuestionsLists { get; set; }
        public virtual ICollection<CreateTemplateModeratingImagesList> CreateTemplateModeratingImagesLists { get; set; }
        public virtual ICollection<CreateTemplateMultipleQuestionsList> CreateTemplateMultipleQuestionsLists { get; set; }
        public virtual ICollection<CreateTemplateTextBoxQuestionsList> CreateTemplateTextBoxQuestionsLists { get; set; }
        public virtual User User { get; set; }
    }
}
