//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M2E.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class facebookPageLikeMapping
    {
        public int Id { get; set; }
        public string refKey { get; set; }
        public string username { get; set; }
        public System.DateTime DateTime { get; set; }
        public string PageId { get; set; }
        public string UserFacebookId { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
