//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M2E.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.CreateTemplateQuestionInfoes = new HashSet<CreateTemplateQuestionInfo>();
            this.facebookPageLikeMappings = new HashSet<facebookPageLikeMapping>();
            this.UserAlerts = new HashSet<UserAlerts>();
            this.RecommendedBies = new HashSet<RecommendedBy>();
            this.UserEarningHistories = new HashSet<UserEarningHistory>();
            this.UserJobMappings = new HashSet<UserJobMapping>();
            this.UserReputationMappings = new HashSet<UserReputationMapping>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string isActive { get; set; }
        public string Type { get; set; }
        public string Source { get; set; }
        public string guid { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ImageUrl { get; set; }
        public string gender { get; set; }
        public string Locked { get; set; }
        public string KeepMeSignedIn { get; set; }
        public string RegistrationTime { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string FacebookLink { get; set; }
        public string LinkedinLink { get; set; }
        public string GoogleLink { get; set; }
        public string fixedGuid { get; set; }
        public string isVerified { get; set; }
    
        public virtual ICollection<CreateTemplateQuestionInfo> CreateTemplateQuestionInfoes { get; set; }
        public virtual FacebookAuth FacebookAuth { get; set; }
        public virtual ICollection<facebookPageLikeMapping> facebookPageLikeMappings { get; set; }
        public virtual ForgetPassword ForgetPassword { get; set; }
        public virtual ICollection<UserAlerts> UserAlerts { get; set; }
        public virtual ICollection<RecommendedBy> RecommendedBies { get; set; }
        public virtual UserEarning UserEarning { get; set; }
        public virtual ICollection<UserEarningHistory> UserEarningHistories { get; set; }
        public virtual ICollection<UserJobMapping> UserJobMappings { get; set; }
        public virtual UserReputation UserReputation { get; set; }
        public virtual ICollection<UserReputationMapping> UserReputationMappings { get; set; }
    }
}
