//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M2E.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMultipleJobMapping
    {
        public int Id { get; set; }
        public string refKey { get; set; }
        public string username { get; set; }
        public string startTime { get; set; }
        public string type { get; set; }
        public string subType { get; set; }
        public string status { get; set; }
        public string endTime { get; set; }
        public string expectedDelivery { get; set; }
        public string surveyResult { get; set; }
    }
}
