//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M2E.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreateTemplateQuestionInfo
    {
        public int Id { get; set; }
        public string username { get; set; }
        public string type { get; set; }
        public string visible { get; set; }
        public string buttonText { get; set; }
        public string referenceId { get; set; }
        public string total { get; set; }
        public string completed { get; set; }
        public string verified { get; set; }
        public string creationTime { get; set; }
        public string title { get; set; }
        public string subType { get; set; }
    }
}
