//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M2E.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreateTemplateModeratingImagesList
    {
        public int Id { get; set; }
        public string username { get; set; }
        public string assignedTo { get; set; }
        public string assignTime { get; set; }
        public string completedAt { get; set; }
        public string referenceKey { get; set; }
        public string deletehash { get; set; }
        public string link { get; set; }
        public int CreateTemplateQuestionInfoId { get; set; }
    
        public virtual CreateTemplateQuestionInfo CreateTemplateQuestionInfo { get; set; }
    }
}
